version: '3.8'
services:
  api:
    build: .
    restart: on-failure:5
    ports:
      - "${PORT}:${PORT}"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
