version: '3.9'
services:
  api:
    build: .
    volumes:
      - ./env:/app/env
  db:
    image: 'mysql:latest'
    environment:
      - MYSQL_PASSWORD: "${DB_PASSWORD}"
      - MYSQL_USER: "${DB_USERNAME}"
      - MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ./schema.sql:/schema.sql
    command:
      - "mysql -u ${MYSQL_USER} -p ${MYSQL_PASSWORD} ${MYSQL_DATABASE} < /schema.sql"
    ports:
      - "3306:3306"

