name: CI/CD Needs
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn
      - run: yarn lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn
      - run: yarn test
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn
      - run: yarn build:prod
